import requests

def fetch_data(url):
    response = requests.get(url)
    if response.status_code == 200:
        print(f"Data fetched successfully from {url}")
        print(response.json())
    else:
        print(f"Failed to fetch data from {url}")

if __name__ == "__main__":
    url = "https://jsonplaceholder.typicode.com/posts"
    fetch_data(url)
